/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddExpenseRouteImport } from './routes/add-expense'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as EditExpenseIdRouteImport } from './routes/edit-expense.$id'
import { Route as FamilyBudgetIndexRouteImport } from './routes/family-budget/index'
import { Route as FamilyBudgetFamilyIdRouteImport } from './routes/family-budget/$familyId'
import { Route as FamilyBudgetFamilyIdMemberMemberIdRouteImport } from './routes/family-budget_.$familyId_.member.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddExpenseRoute = AddExpenseRouteImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const EditExpenseIdRoute = EditExpenseIdRouteImport.update({
  id: '/edit-expense/$id',
  path: '/edit-expense/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyBudgetIndexRoute = FamilyBudgetIndexRouteImport.update({
  id: '/family-budget/',
  path: '/family-budget/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyBudgetFamilyIdRoute = FamilyBudgetFamilyIdRouteImport.update({
  id: '/family-budget/$familyId',
  path: '/family-budget/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyBudgetFamilyIdMemberMemberIdRoute =
  FamilyBudgetFamilyIdMemberMemberIdRouteImport.update({
    id: '/family-budget_/$familyId_/member/$memberId',
    path: '/family-budget/$familyId/member/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-expense': typeof AddExpenseRoute
  '/budget': typeof BudgetRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/edit-expense/$id': typeof EditExpenseIdRoute
  '/family-budget/$familyId': typeof FamilyBudgetFamilyIdRoute
  '/family-budget/': typeof FamilyBudgetIndexRoute
  '/family-budget/$familyId/member/$memberId': typeof FamilyBudgetFamilyIdMemberMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-expense': typeof AddExpenseRoute
  '/budget': typeof BudgetRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/edit-expense/$id': typeof EditExpenseIdRoute
  '/family-budget/$familyId': typeof FamilyBudgetFamilyIdRoute
  '/family-budget': typeof FamilyBudgetIndexRoute
  '/family-budget/$familyId/member/$memberId': typeof FamilyBudgetFamilyIdMemberMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-expense': typeof AddExpenseRoute
  '/budget': typeof BudgetRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/edit-expense/$id': typeof EditExpenseIdRoute
  '/family-budget/$familyId': typeof FamilyBudgetFamilyIdRoute
  '/family-budget/': typeof FamilyBudgetIndexRoute
  '/family-budget_/$familyId_/member/$memberId': typeof FamilyBudgetFamilyIdMemberMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-expense'
    | '/budget'
    | '/expenses'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/signup'
    | '/edit-expense/$id'
    | '/family-budget/$familyId'
    | '/family-budget/'
    | '/family-budget/$familyId/member/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-expense'
    | '/budget'
    | '/expenses'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/signup'
    | '/edit-expense/$id'
    | '/family-budget/$familyId'
    | '/family-budget'
    | '/family-budget/$familyId/member/$memberId'
  id:
    | '__root__'
    | '/'
    | '/add-expense'
    | '/budget'
    | '/expenses'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/signup'
    | '/edit-expense/$id'
    | '/family-budget/$familyId'
    | '/family-budget/'
    | '/family-budget_/$familyId_/member/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddExpenseRoute: typeof AddExpenseRoute
  BudgetRoute: typeof BudgetRoute
  ExpensesRoute: typeof ExpensesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  EditExpenseIdRoute: typeof EditExpenseIdRoute
  FamilyBudgetFamilyIdRoute: typeof FamilyBudgetFamilyIdRoute
  FamilyBudgetIndexRoute: typeof FamilyBudgetIndexRoute
  FamilyBudgetFamilyIdMemberMemberIdRoute: typeof FamilyBudgetFamilyIdMemberMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-expense': {
      id: '/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AddExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-expense/$id': {
      id: '/edit-expense/$id'
      path: '/edit-expense/$id'
      fullPath: '/edit-expense/$id'
      preLoaderRoute: typeof EditExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-budget/': {
      id: '/family-budget/'
      path: '/family-budget'
      fullPath: '/family-budget/'
      preLoaderRoute: typeof FamilyBudgetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-budget/$familyId': {
      id: '/family-budget/$familyId'
      path: '/family-budget/$familyId'
      fullPath: '/family-budget/$familyId'
      preLoaderRoute: typeof FamilyBudgetFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-budget_/$familyId_/member/$memberId': {
      id: '/family-budget_/$familyId_/member/$memberId'
      path: '/family-budget/$familyId/member/$memberId'
      fullPath: '/family-budget/$familyId/member/$memberId'
      preLoaderRoute: typeof FamilyBudgetFamilyIdMemberMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddExpenseRoute: AddExpenseRoute,
  BudgetRoute: BudgetRoute,
  ExpensesRoute: ExpensesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  EditExpenseIdRoute: EditExpenseIdRoute,
  FamilyBudgetFamilyIdRoute: FamilyBudgetFamilyIdRoute,
  FamilyBudgetIndexRoute: FamilyBudgetIndexRoute,
  FamilyBudgetFamilyIdMemberMemberIdRoute:
    FamilyBudgetFamilyIdMemberMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
