/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Prompt to claim clients immediately (for autoUpdate)
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Google Fonts caching
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
      })
    ]
  })
);

// Firebase Configuration (we can safely use import.meta.env here since Vite processes this file)
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_WEB_API_KEY,
  authDomain: "expensemanager-36736.firebaseapp.com",
  projectId: "expensemanager-36736",
  storageBucket: "expensemanager-36736.firebasestorage.app",
  messagingSenderId: "1060457615492",
  appId: "1:1060457615492:web:2f171aa91a3e86a23c32d1",
};

// Initialize Firebase only if API key is present
if (firebaseConfig.apiKey) {
  const app = initializeApp(firebaseConfig);
  const messaging = getMessaging(app);

  onBackgroundMessage(messaging, (payload) => {
    console.log('[sw.ts] Received background message ', payload);
    
    const notificationTitle = payload.notification?.title || 'Expense Manager';
    const notificationOptions = {
      body: payload.notification?.body,
      icon: '/pwa-192x192.png',
      data: {
        url: payload.data?.url || '/',
        ...payload.data
      }
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
  });
}

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, open a new window/tab
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
